import type { Metadata } from "next";

import Header from "@/components/common/header";

import "./globals.css";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import Error from "./error";
import Footer from "@/components/common/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <ErrorBoundary errorComponent={Error}>
          <main>{children}</main>
          {modal}
        </ErrorBoundary>
        <Footer />
      </body>
    </html>
  );
}
